name:                iot-server
version:             0.2.0
github:              "ovanr/IoT-Server"
license:             GPL-2
author:              "Orpheas van Rooij"
maintainer:          "orpheas.vanrooij@outlook.com"
copyright:           "2020 Orpheas van Rooij"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ovanr/iot-server#readme>

dependencies:
- base
- amqp
- bytestring
- hslogger
- comonad
- mtl
- transformers
- directory
- influxdb
- extra
- lens
- aeson
- time
- text
- bytestring
- utf8-string
- containers
- zlib
- mysql-haskell
- io-streams
- base64-bytestring
- concurrent-extra
- optparse-applicative
- exceptions
- either
- co-log
- co-log-core
- transformers
- QuickCheck
- Cabal
- process 
- shelly
- unordered-containers
- vector
- network-uri
- proto-lens
- proto-lens-jsonpb
- proto-lens-runtime
- proto-lens-protobuf-types
- yesod
- yesod-core
- yaml
- wai
- wai-extra
- warp
- template-haskell
- http-client
- http-types
- conduit
- ghc-prim

library:
  source-dirs: src

executables:
  iot-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -fwarn-unused-imports 
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iot-server

tests:
  iot-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iot-server
