/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package iot-server-0.1.0.0 */
#ifndef VERSION_iot_server
#define VERSION_iot_server "0.1.0.0"
#endif /* VERSION_iot_server */
#ifndef MIN_VERSION_iot_server
#define MIN_VERSION_iot_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_iot_server */

/* package aeson-1.5.5.1 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.5.5.1"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 5)
#endif /* MIN_VERSION_aeson */

/* package amqp-0.20.0.1 */
#ifndef VERSION_amqp
#define VERSION_amqp "0.20.0.1"
#endif /* VERSION_amqp */
#ifndef MIN_VERSION_amqp
#define MIN_VERSION_amqp(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  20 || \
  (major1) == 0 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_VERSION_amqp */

/* package base-4.14.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 1)
#endif /* MIN_VERSION_base */

/* package base64-bytestring-1.1.0.0 */
#ifndef VERSION_base64_bytestring
#define VERSION_base64_bytestring "1.1.0.0"
#endif /* VERSION_base64_bytestring */
#ifndef MIN_VERSION_base64_bytestring
#define MIN_VERSION_base64_bytestring(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_base64_bytestring */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package comonad-5.0.8 */
#ifndef VERSION_comonad
#define VERSION_comonad "5.0.8"
#endif /* VERSION_comonad */
#ifndef MIN_VERSION_comonad
#define MIN_VERSION_comonad(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 8)
#endif /* MIN_VERSION_comonad */

/* package concurrent-extra-0.7.0.12 */
#ifndef VERSION_concurrent_extra
#define VERSION_concurrent_extra "0.7.0.12"
#endif /* VERSION_concurrent_extra */
#ifndef MIN_VERSION_concurrent_extra
#define MIN_VERSION_concurrent_extra(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_concurrent_extra */

/* package containers-0.6.2.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.2.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 2)
#endif /* MIN_VERSION_containers */

/* package exceptions-0.10.4 */
#ifndef VERSION_exceptions
#define VERSION_exceptions "0.10.4"
#endif /* VERSION_exceptions */
#ifndef MIN_VERSION_exceptions
#define MIN_VERSION_exceptions(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 4)
#endif /* MIN_VERSION_exceptions */

/* package hslogger-1.3.1.0 */
#ifndef VERSION_hslogger
#define VERSION_hslogger "1.3.1.0"
#endif /* VERSION_hslogger */
#ifndef MIN_VERSION_hslogger
#define MIN_VERSION_hslogger(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_hslogger */

/* package influxdb-1.9.0 */
#ifndef VERSION_influxdb
#define VERSION_influxdb "1.9.0"
#endif /* VERSION_influxdb */
#ifndef MIN_VERSION_influxdb
#define MIN_VERSION_influxdb(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_influxdb */

/* package io-streams-1.5.2.0 */
#ifndef VERSION_io_streams
#define VERSION_io_streams "1.5.2.0"
#endif /* VERSION_io_streams */
#ifndef MIN_VERSION_io_streams
#define MIN_VERSION_io_streams(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 2)
#endif /* MIN_VERSION_io_streams */

/* package iot-shared-0.1.0.0 */
#ifndef VERSION_iot_shared
#define VERSION_iot_shared "0.1.0.0"
#endif /* VERSION_iot_shared */
#ifndef MIN_VERSION_iot_shared
#define MIN_VERSION_iot_shared(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_iot_shared */

/* package lens-4.19.2 */
#ifndef VERSION_lens
#define VERSION_lens "4.19.2"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  19 || \
  (major1) == 4 && (major2) == 19 && (minor) <= 2)
#endif /* MIN_VERSION_lens */

/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */

/* package mysql-haskell-0.8.4.3 */
#ifndef VERSION_mysql_haskell
#define VERSION_mysql_haskell "0.8.4.3"
#endif /* VERSION_mysql_haskell */
#ifndef MIN_VERSION_mysql_haskell
#define MIN_VERSION_mysql_haskell(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_VERSION_mysql_haskell */

/* package optparse-applicative-0.15.1.0 */
#ifndef VERSION_optparse_applicative
#define VERSION_optparse_applicative "0.15.1.0"
#endif /* VERSION_optparse_applicative */
#ifndef MIN_VERSION_optparse_applicative
#define MIN_VERSION_optparse_applicative(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 1)
#endif /* MIN_VERSION_optparse_applicative */

/* package text-1.2.4.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package time-1.9.3 */
#ifndef VERSION_time
#define VERSION_time "1.9.3"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 3)
#endif /* MIN_VERSION_time */

/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */

/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */

/* package zlib-0.6.2.2 */
#ifndef VERSION_zlib
#define VERSION_zlib "0.6.2.2"
#endif /* VERSION_zlib */
#ifndef MIN_VERSION_zlib
#define MIN_VERSION_zlib(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 2)
#endif /* MIN_VERSION_zlib */

/* tool gcc-10.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "10.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  10 || \
  (major1) == 10 && (major2) <  2 || \
  (major1) == 10 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-1.7.3 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.7.3"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  7 || \
  (major1) == 1 && (major2) == 7 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.36 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.36"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  36 || \
  (major1) == 2 && (major2) == 36 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "iot-server-0.1.0.0-FojVdoyl8odLcQgDFPdrq9"
#endif /* CURRENT_PACKAGE_KEY */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "iot-server-0.1.0.0-FojVdoyl8odLcQgDFPdrq9"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package iot-server-0.1.0.0 */
#ifndef VERSION_iot_server
#define VERSION_iot_server "0.1.0.0"
#endif /* VERSION_iot_server */
#ifndef MIN_VERSION_iot_server
#define MIN_VERSION_iot_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_iot_server */

/* package aeson-1.5.5.1 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.5.5.1"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 5)
#endif /* MIN_VERSION_aeson */

/* package amqp-0.20.0.1 */
#ifndef VERSION_amqp
#define VERSION_amqp "0.20.0.1"
#endif /* VERSION_amqp */
#ifndef MIN_VERSION_amqp
#define MIN_VERSION_amqp(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  20 || \
  (major1) == 0 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_VERSION_amqp */

/* package base-4.14.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 1)
#endif /* MIN_VERSION_base */

/* package base64-bytestring-1.1.0.0 */
#ifndef VERSION_base64_bytestring
#define VERSION_base64_bytestring "1.1.0.0"
#endif /* VERSION_base64_bytestring */
#ifndef MIN_VERSION_base64_bytestring
#define MIN_VERSION_base64_bytestring(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_base64_bytestring */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package comonad-5.0.8 */
#ifndef VERSION_comonad
#define VERSION_comonad "5.0.8"
#endif /* VERSION_comonad */
#ifndef MIN_VERSION_comonad
#define MIN_VERSION_comonad(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 8)
#endif /* MIN_VERSION_comonad */

/* package concurrent-extra-0.7.0.12 */
#ifndef VERSION_concurrent_extra
#define VERSION_concurrent_extra "0.7.0.12"
#endif /* VERSION_concurrent_extra */
#ifndef MIN_VERSION_concurrent_extra
#define MIN_VERSION_concurrent_extra(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_concurrent_extra */

/* package containers-0.6.2.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.2.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 2)
#endif /* MIN_VERSION_containers */

/* package exceptions-0.10.4 */
#ifndef VERSION_exceptions
#define VERSION_exceptions "0.10.4"
#endif /* VERSION_exceptions */
#ifndef MIN_VERSION_exceptions
#define MIN_VERSION_exceptions(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 4)
#endif /* MIN_VERSION_exceptions */

/* package hslogger-1.3.1.0 */
#ifndef VERSION_hslogger
#define VERSION_hslogger "1.3.1.0"
#endif /* VERSION_hslogger */
#ifndef MIN_VERSION_hslogger
#define MIN_VERSION_hslogger(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_hslogger */

/* package influxdb-1.9.0 */
#ifndef VERSION_influxdb
#define VERSION_influxdb "1.9.0"
#endif /* VERSION_influxdb */
#ifndef MIN_VERSION_influxdb
#define MIN_VERSION_influxdb(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_influxdb */

/* package io-streams-1.5.2.0 */
#ifndef VERSION_io_streams
#define VERSION_io_streams "1.5.2.0"
#endif /* VERSION_io_streams */
#ifndef MIN_VERSION_io_streams
#define MIN_VERSION_io_streams(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 2)
#endif /* MIN_VERSION_io_streams */

/* package iot-server-0.1.0.0 */
#ifndef VERSION_iot_server
#define VERSION_iot_server "0.1.0.0"
#endif /* VERSION_iot_server */
#ifndef MIN_VERSION_iot_server
#define MIN_VERSION_iot_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_iot_server */

/* package iot-shared-0.1.0.0 */
#ifndef VERSION_iot_shared
#define VERSION_iot_shared "0.1.0.0"
#endif /* VERSION_iot_shared */
#ifndef MIN_VERSION_iot_shared
#define MIN_VERSION_iot_shared(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_iot_shared */

/* package lens-4.19.2 */
#ifndef VERSION_lens
#define VERSION_lens "4.19.2"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  19 || \
  (major1) == 4 && (major2) == 19 && (minor) <= 2)
#endif /* MIN_VERSION_lens */

/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */

/* package mysql-haskell-0.8.4.3 */
#ifndef VERSION_mysql_haskell
#define VERSION_mysql_haskell "0.8.4.3"
#endif /* VERSION_mysql_haskell */
#ifndef MIN_VERSION_mysql_haskell
#define MIN_VERSION_mysql_haskell(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_VERSION_mysql_haskell */

/* package optparse-applicative-0.15.1.0 */
#ifndef VERSION_optparse_applicative
#define VERSION_optparse_applicative "0.15.1.0"
#endif /* VERSION_optparse_applicative */
#ifndef MIN_VERSION_optparse_applicative
#define MIN_VERSION_optparse_applicative(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 1)
#endif /* MIN_VERSION_optparse_applicative */

/* package text-1.2.4.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package time-1.9.3 */
#ifndef VERSION_time
#define VERSION_time "1.9.3"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 3)
#endif /* MIN_VERSION_time */

/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */

/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */

/* package zlib-0.6.2.2 */
#ifndef VERSION_zlib
#define VERSION_zlib "0.6.2.2"
#endif /* VERSION_zlib */
#ifndef MIN_VERSION_zlib
#define MIN_VERSION_zlib(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 2)
#endif /* MIN_VERSION_zlib */

/* tool gcc-10.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "10.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  10 || \
  (major1) == 10 && (major2) <  2 || \
  (major1) == 10 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-1.7.3 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.7.3"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  7 || \
  (major1) == 1 && (major2) == 7 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.36 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.36"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  36 || \
  (major1) == 2 && (major2) == 36 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "iot-server-0.1.0.0-3Xo9Ma4xBDdHtXygnWLrfT-iot-server"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
