-- Code generated by protoc-gen-jsonpb_haskell 0.1.1, DO NOT EDIT.
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-orphans -Wno-unused-imports -Wno-missing-export-lists #-}
module Proto.Cmd.Confupdatedt_JSON where

import           Prelude(($), (.), (<$>), pure, show, Maybe(..))

import           Data.ProtoLens.Runtime.Lens.Family2 ((^.), (.~), (&))
import           Data.Monoid (mconcat)
import           Control.Monad (msum)
import           Data.ProtoLens (defMessage)
import qualified Data.Aeson as A
import qualified Data.Aeson.Encoding as E
import           Data.ProtoLens.JSONPB as JSONPB
import qualified Data.Text as T

import           Proto.Configdt_JSON ()
import           Proto.Cmd.Confupdatedt as P
import           Proto.Cmd.Confupdatedt_Fields as P

instance FromJSONPB Confupdateopt where
  parseJSONPB = withObject "Confupdateopt" $ \obj -> do
    perform' <- obj .: "perform"
    newConf' <- obj A..:? "newConf"
    pure $ defMessage
      & P.perform .~ perform'
      & P.maybe'newConf .~ newConf'

instance ToJSONPB Confupdateopt where
  toJSONPB x = object
    [ "perform" .= (x^.perform)
    , "newConf" .= (x^.maybe'newConf)
    ]
  toEncodingPB x = pairs
    [ "perform" .= (x^.perform)
    , "newConf" .= (x^.maybe'newConf)
    ]

instance FromJSON Confupdateopt where
  parseJSON = parseJSONPB

instance ToJSON Confupdateopt where
  toJSON = toAesonValue
  toEncoding = toAesonEncoding
